spring.application.name=bloomix-admin-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

spring.session.timeout=2h
spring.session.data.redis.namespace=bloomix:admin:session

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

management.endpoints.web.exposure.include=health,info
